namespace TaUtilities
{
	public enum MessageType
	{
		UNKNOWN_MESSAGE,
		OPERATION_FAILED,
		CREATE_LOBBY,
		LOBBY_CREATED,
		REMOVE_LOBBY,
		LOBBY_REMOVED,
		JOIN_LOBBY,
		LOBBY_JOINED,
		LEAVE_LOBBY,
		LOBBY_LEFT,
		KICK_PLAYER,
		PLAYER_KICKED,
		START_DOWNLOAD,
		DOWNLOAD_STARTED,
		DOWNLOAD_FILE,
		DOWNLOAD_FINISHED,
		DOWNLOADS_FINISHED,
		DOWNLOAD_STATUS
	}
}
